name: Build Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  pull_request_target:

  workflow_dispatch:
    
env:
  DOTNET_VERSION: '8.0.x'
  
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  repository-projects: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  BuildAndTestApplication:
    environment:
      name: develop
      #url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install DotNet Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Test application
        run: dotnet test --no-build --verbosity normal
      
  CreatePullRequest:
    needs: BuildAndTestApplication
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create pull request #Etapa de criação do pull request usando o cli do github
        run: gh pr create -B main -H develop --title 'Merge Develop into Main' --body 'Created automatic Pull Request by Github action.'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  AutoAprove:
    needs: CreatePullRequest
    runs-on: ubuntu-latest 
      
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: hmarr/auto-approve-action@v4